### ISSUE TITLE
Promisify Twitter API

### ISSUE THREAD

**Issue by jsha** [jsha/blocktogether#118]
This may be as simple as using Bluebird's promisifyAll, and then modifying the various call sites. This would clean up the code for interacting with Twitter.

**Comment by doeg** [comment]
This sounds fun. I'll keep it on my radar after I get through a few of the #goodfirstbugs :dog:

**Comment by jsha** [comment]
BTW, it might be nice to do the promisification as part of the node-twitter-api library, and contribute it upstream. I have a local copy in this repo (because it depends on a change I made in the oauth npm to accept an Agent param), so you can edit locally and then copy into the node-twitter-api library, or work directly on the node-twitter-api library, get it accepted upstream, then pull down the changes. The author is quite responsive on change requests.

**Comment by jsha** [comment]
I believe all calls to the Twitter API now use Q.ninvoke, since the app is essentially all promisified now.
