### ISSUE TITLE
Vagrantfile/Dockerfile

### ISSUE THREAD

**Issue by zchrykng** [jsha/blocktogether#143]
I ran into a bit of trouble getting this running on a VM, (mainly seemed to be some database access stuff... not sure exactly what the problem was though). Anyway, thought it would be nice if someone setup a Vagrantfile or Dockerfile to ease contributions by those with less technical skills. I might work on this if I have time, but not sure when that will be.

**Comment by doeg** [comment]
I'm happy to work on this today. :)

**Comment by doeg** [comment]
Fixed.
