### ISSUE TITLE
My Blocks don't update

### ISSUE THREAD

**Issue by GreatSalamander** [jsha/blocktogether#145]
After unsubscribing from a block list and bulk un-blocking everyone, the "My Blocks" still says I'm blocking people.  But when I go to my blocks on twitter, it shows I'm no longer blocking anyone.  Is there a way to update the My Blocks list?

**Comment by jsha** [comment]
Fixed the underlying bug: The keepalive library I was using, yakaa, didn't deal well with connections closed by the server. Yakaa fixed the bug and I upgraded blocktogether.
