### ISSUE TITLE
Login button on post-logoff page does not function - Invalid CSRF Token

### ISSUE THREAD

**Issue by binaryparadox** [jsha/blocktogether#148]
If you log out of Block Together the button to "Log On" again doesn't work. You must go back tot he root of the domain and then log in with that form.

Steps to reproduce:
1. Log in to Blocktogether
2. Click "Log Off" button on the menu in the top right corner. This redirects you to the [logged-out page](https://blocktogether.org/logged-out)
3. Click "Log On" button on the menu in the top right corner.
4. Browser location changes to [/auth/twitter](https://blocktogether.org/auth/twitter) and displays: ``` Error: Object Error: Invalid CSRF token. has no method 'status' ```

![CSRF error screenshot](https://binaryparadox.net/d/021f146f-dad4-4a75-8f72-0e2bc61d79e0.jpg)

**Comment by binaryparadox** [comment]
It looks like the CSRF token is empty in both the form and the body tag data URI on the broken Log On button page compared to the working index log on button.

**Comment by binaryparadox** [comment]
I think the call to [``compileAndRender``](
https://github.com/jsha/blocktogether/blob/bfdec7a0fc5e5230adb842de06eb169b1c8f929d/blocktogether.js#L297) for the ``logged-out.mustache`` template needs the ``csrf_token`` passed into the render context like is done for index.mustache.

I will send a pull req.

**Comment by jsha** [comment]
That sounds right. Thanks for finding and fixing.

I need to find a better solution for all views to share the mustache variables that are expected by the header code. Not sure what the best thing is.
