### ISSUE TITLE
Vagrantfile should refer to a current disk image

### ISSUE THREAD

**Issue by npdoty** [jsha/blocktogether#183]
Per https://github.com/jsha/blocktogether/commit/96933c47f1b56d65d3d90ca080261eb624b306a9#commitcomment-10115327, the fixed snapshot is no longer hosted on the Ubuntu site, so `vagrant up` fails for me on its first attempt. 

I'd suggest (as I did in my working copy just to get things running), pointing to the `current` directory and removing the checksum altogether. If it helps, I can submit a pull request to that effect. I don't know a way to include a reliable checksum that way, but so it goes.

**Comment by harrounmoussa** [comment]
Hi,

I've implement a fix in this PR: #198
@jsha can you accept it ?
