### ISSUE TITLE
Hide blocklist before signing up to the list

### ISSUE THREAD

**Issue by oqpied** [jsha/blocktogether#200]
Dear Jacob,
As an adviser for several entities that are often the target for many trolls on Twitter, I've used your app and found it potentially very helpful, however, with one particular flaw which costed me even more headache from trolls :-)
Your app displays the blocked accounts list on the signup form. The relentless trolls could spot their accounts and took measures to redirect their attacks through different account not appearing on the list. The use of your app ended up inviting yet another nasty trolling wave upon my clients.
My suggestion is to reveal the blocklist only to those who signup for the list AFTER THEY SIGN.
This simple modulation will prevent the trolls from figuring which one of their accounts is featured and which isn't.
A small descriptive field could be added for user to define and describe the list...

**Comment by jsha** [comment]
Hi @oqpied! I definitely appreciate your use case, but based on the past experience of The Block Bot, Twitter considers it necessary to show people the list of accounts they will block before blocking them. I think this is a good policy, too: people can't effectively decide whether they want to use a given block list unless they can see who is on it.
