### ISSUE TITLE
i deactivated for a week and now my blocklist is gone

### ISSUE THREAD

**Issue by suisea** [jsha/blocktogether#206]
also i don't know if being private affects it? it shouldn't, right? anyway a LOT of accounts depend on my blocklist, so this is a huge vulnerability. (i'm @swayandsea on twitter, fyi)

**Comment by jsha** [comment]
Thanks for the report! I'll take a look. Block Together does hide block lists when their owner is deactivated, deleted or suspended, but it should bring them back once the account is back (up to 30 days). The check for reactivation happens about once a day, though it's possible it's broken. When did you reactivate?

**Comment by suisea** [comment]
i reactivated like a week ago? i was only deactivated for 5 days!

**Comment by suisea** [comment]
okay, i logged back in and now i have a new url apparently? um

this is my old one:
https://blocktogether.org/show-blocks/WEBquZTRVk8ke5jZSi7rPrC7HClyGIklbt9MnIO6

this is my new one:
https://blocktogether.org/show-blocks/C3k17uZy9f0BgtEJHdO893d8Z00AzT6dTiK-8sUK

but what about all the people subscribed to my old one??? is there a way to just redirect the 2nd link to the 1st? x_x

**Comment by jsha** [comment]
You should still have all your subscribers - check the subscriptions tab. I
can manually edit the URL to make it match the old one, if you have links
to it in a lot of places.

Also, your subscribers still have all their blocks - even if your block
list goes away, their blocks remain.

**Comment by suisea** [comment]
yes pls manually edit it! thank you ✨

**Comment by jsha** [comment]
Done: your old URL is restored.

**Comment by suisea** [comment]
thank you so much! :D
