### ISSUE TITLE
Curated Block Lists

### ISSUE THREAD

**Issue by bkerensa** [jsha/blocktogether#221]
Would be nice if like ad block there were lists of abusive people we could opt-in to blocking from the get go like known abusers and trolls.

**Comment by fuhrmanator** [comment]
Agree. I get these NSFW followers (adult-oriented content) and the only way to block is to visit their stinking profile and see the NSFW content. (can't believe there's no easier way). I'd like to auto-block any of these accounts that likes/follows me. It's spam pure and simple. They even sometimes put me on their "lists" and I get a notification. BLOCK BLOCK BLOCK them all.

Adblock has curated lists (https://easylist.github.io/), so do anti-spam systems (e.g. http://www.dnsbl.info/). Twitter is overdue for "proactive" blocking.

**Comment by alanhuang122** [comment]
Or, for example, "BUY FOLLOWERS NOW"

**Comment by pjclutterbuck** [comment]
+1

**Comment by jsha** [comment]
Thanks for the suggestion! I'm afraid I don't have the bandwidth to maintain a list of recommended block lists, but people are welcome to start their own lists!
