### ISSUE TITLE
Unblocking many accounts at once throws Internal Server Error

### ISSUE THREAD

**Issue by KonomiKitten** [jsha/blocktogether#222]
I subscribed to a rather large bot blocklist much to my error, it seems when trying to unblock 4 pages of accounts or more Blocktogether will throw "Error: error Internal Server Error".

![error Internal Server Error](https://cloud.githubusercontent.com/assets/12713710/17513100/643ee194-5e6e-11e6-9ede-02b47cc3a52c.png)

**Comment by jsha** [comment]
I've made some improvements. If this continues to reproduce, please reopen.
