### ISSUE TITLE
Auto-block people who likes / shares tweets from blocked people in which you got mentioned.

### ISSUE THREAD

**Issue by PietLu** [jsha/blocktogether#225]
Could you please add the feature to auto-block accounts, that like or retweet tweets from people from your blocklist, in which they mention you?
Hope, that works and isn't impossible :D

**Comment by jsha** [comment]
Hi @PietLu! That's an interesting idea, but I think it would make Block Together more complex, and I really want to keep it simple. Thanks for suggesting it though!

**Comment by pjclutterbuck** [comment]
+1
