### ISSUE TITLE
Block all followers of someone you blocked

### ISSUE THREAD

**Issue by mojo2344** [jsha/blocktogether#226]
get rid of trolls with many handles, if you can click one button to block everyone who is following a troll

**Comment by spencerthayer** [comment]
This is a genius solution.

**Comment by mgdupont** [comment]
Danger: sometimes famous news reporter Twitter accounts autofollow everyone who autofollows them. If you block a troll and automatically block the people who follow him, you could be blocking famous non-trolls: reporters, celebrities, etc.

**Comment by kmahar** [comment]
maybe only blocks the followers if they start tweeting @ you?

**Comment by mattghali** [comment]
Hi, I have a service that manages this automatically, based on twitter lists: https://github.com/mattghali/enlist

**Comment by jsha** [comment]
Closing since this exists elsewhere and I don't plan to implement it for Block Together.
