### ISSUE TITLE
external blocks don't seem to be updating

### ISSUE THREAD

**Issue by jjb** [jsha/blocktogether#233]
It seems like my external blocks aren't updating. I've blocked a few people recently and they don't show up in Actions. Most recent one is a month ago.

Thanks for a great project!

**Comment by spencerthayer** [comment]
I think this project might be abandoned. I am having similar issues and there doesn't seem to be any attempt to solve it.

**Comment by jsha** [comment]
This is a persistent, occasional problem, but I haven't been able to reproduce it reliably and am not sure of the root cause. Definitely interested in ideas!
