### ISSUE TITLE
Propagate forgiveness

### ISSUE THREAD

**Issue by jsha** [jsha/blocktogether#24]
If person A has a popular block list and puts person B on it, then later decides that was a mistake and unblocks person B, that unblock should propagate through to people who blocked B through A's list.

This is fairly complicated, because if person C is blocking person B because of their presence on A's list, and additionally because of another list where B has not been forgiven, we should *not* unblock.

**Comment by jsha** [comment]
Fixed. Forgiveness will now be propagated.

**Comment by diracdeltas** [comment]
Hand clap emoji here
