### ISSUE TITLE
Completely remove Block Together

### ISSUE THREAD

**Issue by KonomiKitten** [jsha/blocktogether#240]
Is it possible to delete my account from Block Together entirely? If I revoke the app permission is my Block Together account completely gone?

**Comment by jsha** [comment]
If you revoke the app, Block Together no longer has any access to your
Twitter account, and will immediately stop applying blocks and showing your
shared block list (if applicable). Within 30 days, Block Together
automatically deletes your data from its servers.

**Comment by KonomiKitten** [comment]
Thanks for the quick reply, closing issue.
