### ISSUE TITLE
lag in blocklist updating 

### ISSUE THREAD

**Issue by Artimusfoul** [jsha/blocktogether#251]
Hi we're using blocktogether to power a blocklist called @repeal_shield. 
https://blocktogether.org/show-blocks/H4j1pWKFc2wlWh3EA2sHoHn9JhBAgoPF6UJz6SzS

Focusing on mainly on Pro Life/Anti Abortion troll accounts in Ireland (we're about to have a referendum on liberalising our Abortion laws in May). 

We've had some issues, we've had a very big day (massive pro life rally in Dublin) and the block list was showing the last update was 13hrs ago for most of the day (between 2pm - 5pm GMT) And then the list jumped from 2,227 users to over 2,600 (we had alot of trolls), sorry don't have a screengrab and several users are reporting a significant lag between our blocking an acc and the block list taking effect. 

I'm not a programmer of any sort, so can't provide any technical details beyond this, but am happy to answer any questions you have , if you are able to help. 

Regards

Aidan
@artimusfoul
@repeal_shield

**Comment by jsha** [comment]
There were some occasional load issues leading to slow updates. I checked now, and your list is up-to-date. Sorry for the trouble!
