### ISSUE TITLE
More transparency

### ISSUE THREAD

**Issue by al45tair** [jsha/blocktogether#254]
While individuals' own blocks should remain private, I think there's a really good case for a bit of transparency when blocklists are shared (such as via block together), *particularly* with large or popular blocklists. In particular:

- It should be possible for users of Twitter to find out whether they are on a shared blocklist and to at least message its owner to ask why they were added to it (the message can be fixed form, to avoid any problem of abuse by people who were blocked for a good reason).
- It should be possible to users added to a blocklist to indicate that they feel they've been added unfairly or spuriously. It might make sense for users to be able to publicly comment on block lists for this purpose (since that will allow others to see examples of Twitter accounts that consider they've been blocked unfairly, which gives a way to evaluate whether the policies of a given block list are sane or not).
- Statistics should be available on blocklists so that users can make an informed choice about whether they want to use them or not; examples include:
    - Number of accounts in block-list
    - Number of *active* accounts in block-list (e.g. number that have tweeted in last 30 days); large numbers of inactive accounts listed may indicate that block-list is badly maintained
    - Proportion of accounts that have indicated they've been added unfairly or spuriously

Without these features, it's difficult for people to sensibly evaluate whether or not they wish to use a shared block-list, particularly a larger or more popular one. The result, right now, is that there will be cases where users are over-blocking in a manner that is under the control of a third party that they've effectively trusted to censor their feed for them, perhaps without appreciating the extent or implications of that decision. There will also be people who won't use shared block lists because they don't have sufficient information to guarantee that they won't end up over-blocking as a result and/or end up in a situation where e.g. a Russian troll farm is able to censor their Twitter feed for them.

**Comment by signe** [comment]
Blocklists which have been shared publicly can already be searched.  Blocklists which are not public (which is almost all of them, since every user with an account has a blocklist) should not be searchable.

![image](https://user-images.githubusercontent.com/249456/41750530-5f787b54-7571-11e8-92f0-5008b632ab52.png)

If you have a link to a blocklist, it already includes the owner's name in the details.  The fact that you're blocked by them means that they don't want to be contacted by you. People who subscribe to that user's blocklist have knowingly made the choice to respect the owner's reasoning for blocking you.

The idea that you are entitled to interrogate someone who has blocked you, or make claims as to the "legitimacy" of their block, whether their blocklist is public or not, is just that — you feeling entitled.  They have the right to block you for any reason at all.

The number of inactive accounts in a list is not an indicator of it being badly maintained.  No one goes through their list to identify whether an account hasn't tweeted in a while to say "Oh, I'll give them another chance if they do come back."  They were blocked for a reason and whether they're still active or not is irrelevant.

The ratio of people who would object to being blocked and would therefore indicate that they were "blocked unfairly" approaches 1; It's a useless metric.

**Comment by al45tair** [comment]
> Blocklists which are not public (which is almost all of them, since every user with an account has a blocklist) should not be searchable.

I did in fact say that individuals' own block lists should not be searchable.

> People who subscribe to that user's blocklist have knowingly made the choice to respect the owner's reasoning for blocking you.

Except they haven't. There are a number of large public blacklists, and the notion that people who subscribe to them have "knowingly made the choice to respect the owner's reasoning" is highly suspect in such cases. It's the same as spam filters, actually; there are a number of RBLs whose listing policies are, well, a little suspect, and people have routinely started using them and only later discovered they were blocking e-mail that they actually wanted to receive.

> The idea that you are entitled to interrogate someone who has blocked you, or make claims as to the "legitimacy" of their block, whether their blocklist is public or not, is just that — you feeling entitled. They have the right to block you for any reason at all.

They do have the right to block you for any reason at all, I quite agree. The problem comes when they are imposing their right to block on others who (a) might not appreciate either that they're blocking you as a result of a shared block list they subscribe to, or (b) might actually _not_ agree with the reasoning behind you being listed.

> The number of inactive accounts in a list is not an indicator of it being badly maintained.

For smaller or private lists, sure, I'd agree with you. But for large public lists, I think it _is_ good practice to expire blocks somehow. I quite understand that most of them don't do this at present, but that's no reason that they shouldn't. Again, this is very similar to RBLs, where most of them _do_ expire listings over time.

> The ratio of people who would object to being blocked and would therefore indicate that they were "blocked unfairly" approaches 1; It's a useless metric.

In your opinion. The fact that someone claims publicly to have been blocked unfairly _is_ an interesting data point; you're right that people who have been blocked following the policy of a block list might well make that claim, but the thing is that you can evaluate that yourself by looking at their account.

How would you propose that someone should evaluate a blocklist at present? Right now, there isn't even a way to tell whether a given list is following its own listing policy (if indeed it bothers explaining what that is). The result is that using a shared blocklist essentially allows whoever is maintaining it to censor Twitter for you; what if the blocklist is maintained by the St Petersburg troll farm, for instance? Do you seriously think the present situation is a good one?

**Comment by signe** [comment]
Subscription to a blocklist is a voluntary, not compulsory, act undertaken with full understanding that it could block people you don't agree with.  This is why when you manually unblock someone, BT will not block them again based on a list action.

If you subscribe to a blocklist, you are stating that you believe the maintainer of said list is blocking people whom you want to also block.  If you disagree with that, you unsubscribe from the list or don't subscribe in the first place.

The majority of Twitter users who are savvy enough to understand the utility of BT are also savvy enough to not subscribe to lists randomly and for no reason.  Popular lists are established by known users and groups of users working toward a common goal.  Mistakes happen and are rectified by the list maintainers.

If someone chooses to blindly subscribe to a list created by a user that they don't validate/already trust, that's no one's fault but their own.

Yes — I absolutely think the current methodology of BT is a good one.  I think that your suggestions allow abusers to continue abusing people who block them and do not benefit the users who are using BT for blocking purposes.

**Comment by al45tair** [comment]
> If you subscribe to a blocklist, you are stating that you believe the maintainer of said list is blocking people whom you want to also block. If you disagree with that, you unsubscribe from the list or don't subscribe in the first place.

It's all well and good saying that, but in practice there will be cases where your belief is incorrect.

The point of this issue report is that BT needs to have tools to allow users to understand whether they _really_ want to subscribe to a block list or not, and, ideally, tools to let users understand the behaviour of lists they are already subscribed to (so that they can see if something untoward starts happening). Right now, it doesn't have those tools. It's quite possible (and indeed sensible, I'd suggest) to have a debate about what tools _should_ be available, but I don't think you can really sensibly argue that the present situation is a good one.

> If someone chooses to blindly subscribe to a list created by a user that they don't validate/already trust, that's no one's fault but their own.

And if they subscribe to a list created by a user that they think they trust, but who then does something untoward? This is clearly quite a common problem on Twitter, which is why the Russian troll farm is so effective.

> I think that your suggestions allow abusers to continue abusing people who block them and do not benefit the users who are using BT for blocking purposes.

How? I'm not proposing that abusers are able to unblock themselves. I'm not even proposing that they should be able to send messages to the maintainer of a block list (except possibly for a system message sent by BT itself, over which they have no control, which could be both aggregated and rate limited to prevent it from being used to annoy someone). I suppose you could take issue with the idea of being able to comment on your inclusion in a block list — that's why I said _might_, because there is certainly a risk of abusive comments, though I don't know that I'd expect blocklist maintainers to pay them much attention anyway, so…

**Comment by jsha** [comment]
Hi! Thanks for the feedback on this. I would definitely like to add more details on the blocklist subscription page to help people evaluate whether they want to subscribe. I'm going to close this issue for now; I'll update via the Twitter account as such features are implemented.
