### ISSUE TITLE
Site is inacessible for days

### ISSUE THREAD

**Issue by vabluebelle18** [jsha/blocktogether#280]
I have been trying to access the blocktogether site for over a week now. I was briefly able to get in yesterday but not today. When I click on "Log on using Twitter" I see it trying to aunthenticate the token but it spins and spins for several minutes then displays the main screen with the error message "Error: This feature is temporarily unavailable". Subscriptions also appear not to be working. I blocked a couple of accounts to test and when I checked the subscribing account the next day the blocks were not propagated to the subscriber.  I have several people who have contacted me saying they are having this same issue. Many of us rely on the subscription capability as the onslaught of targeted reporting is on an upswing on Twitter. Any help would be greatly appreciated!
![BTError](https://user-images.githubusercontent.com/53713514/62430670-85cfc000-b6ed-11e9-8a37-0e4881c243e9.JPG)

**Comment by jsha** [comment]
Sorry for the outage. I've been having disk-full problems. Added some storage; things should be back to normal.

**Comment by jsha** [comment]
Scratch that, looks like something else needs fixing too.

**Comment by vabluebelle18** [comment]
Thank you, thank you, thank you!

**Comment by jsha** [comment]
Alright, fixed now. Thanks for the report!

**Comment by vabluebelle18** [comment]
Jacob I thank you so very much. Do you have anything setup where we can
donate to you as I would very much like to do that and I know others would
as well!
