### ISSUE TITLE
Blocktogether is down

### ISSUE THREAD

**Issue by Vabluebelle17** [jsha/blocktogether#290]
Came back sometime yesterday but is down again today. Sticks in authorization for about a minute or so then displays error message "Error: This feature is temporarily unavailable". I have someone who subscribed to one of my lists two days ago and when she was briefly able to get into Blocktogether it was still showing Pending for all. She refreshed screen and got a Gateway 504 message and now neither of us are able to login to the app. Appreciate some help and Happy Holidays!

**Comment by zacanger** [comment]
Duplicate of #286, probably

**Comment by zacanger** [comment]
This seems to be fixed now.

**Comment by dankegel** [comment]
Uptime did seem a bit low a week ago, ok now...

**Comment by Vabluebelle17** [comment]
Appears to be working now. Thanks!
