### ISSUE TITLE
Blocklist combinators (AND, OR)

### ISSUE THREAD

**Issue by SoniEx2** [jsha/blocktogether#292]
When you have an allowlist with multiple inheritance, instead of a blocklist with multiple inheritance, you get some interesting behaviours with regards to *loops*.

It'd be cool if blocklists could also have that same behaviour. That is, if an account isn't blocked by all upstream blocklists, then it doesn't get included unless you block it too. This gives you a "threshold" feature for blocking and prevents gaslighting, isolation, and general block-based abuse, which are things that happen a lot in marginalized communities.

This should be opt-in ofc but that's the idea.

**Comment by jsha** [comment]
Thanks for the idea! This is a little more complicated than I want to implement, but it's a cool concept.
