### ISSUE TITLE
Can't Update Blocklist

### ISSUE THREAD

**Issue by Birbles** [jsha/blocktogether#306]
Hi, my block list is saying that it has 0 blocks and hasn't been updated in a year. Is there any way to update this? 
I saw the other issue someone was having with being unable to update their list but it seems to be different since theirs was only not updating for a few days and I wasn't sure if I should revive an old thread.
Any help would be appreciated.

**Comment by jsha** [comment]
Thanks for the report - the database was refusing connections from the component that updates blocks. I've fixed it and things seem to be working again.

**Comment by Birbles** [comment]
My blocklist still isn't updating
