### ISSUE TITLE
MIgrate to ES6

### ISSUE THREAD

**Issue by SukkaW** [jsha/blocktogether#317]
Hi, it appears that the project is based on "old" JavaScript.

It there any plan to migrate the code to ES6 (and run with Node.js)? I could help on migration & drop lodash.

**Comment by jsha** [comment]
The code does in fact use a good number of ES6 features, like arrow functions and consts, and it even uses async/await from ES8. I haven't fully converted everything to newer idioms, but also the project will be shutting down (https://blocktogether.org/shutdown.html) so I am not planning to invest in refactorings like that.
