### ISSUE TITLE
Thanks for all your work over the years

### ISSUE THREAD

**Issue by zautumnz** [jsha/blocktogether#318]
@jsha and other contributors: I just saw the announcement on the site, and wanted to say thanks. I'm sure it wasn't an easy decision to come to. All your users are grateful for all the work (and money) you put into this over the years.

**Comment by jsha** [comment]
Thanks so much @zacanger! It really warms my heart to hear this. You're right that it wasn't an easy decision, and I'm glad it has been met with kindness and understanding.
