### ISSUE TITLE
Search within blocklists

### ISSUE THREAD

**Issue by jsha** [jsha/blocktogether#99]
Now that blocklists are paginated, it can be a lot harder to find whether a given user is on a list. There should be an option to search within a blocklist (including your own) for a string that matches screen name or display name.

**Comment by doeg** [comment]
Using SlickGrid (#150) should make searching/filtering lists very straightforward on the client-side. (Disclaimer: I haven't delved into the back-end stuff yet.)

**Comment by jsha** [comment]
Fixed.
